export const AGREGAR_CARRITO = "AGREGAR_CARRITO";
export const AGREGAR_CARRITO_EXITO = "AGREGAR_CARRITO_EXITO";
export const AGREGAR_CARRITO_ERROR = "AGREGAR_CARRITO_ERROR";

export const ID_PRODUCTO = "ID_PRODUCTO";
export const ID_PRODUCTO_ADD = "ID_PRODUCTO_ADD";
export const ID_PRODUCTO_ERROR = "ID_PRODUCTO_ERROR";

export const ELIMINAR_PRODUCTO_CARRITO = "ELIMINAR_PRODUCTO_CARRITO";
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO";
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR";

export const AGREGAR_PEDIDO = "AGREGAR_PEDIDO";
export const AGREGAR_PEDIDO_EXITO = "AGREGAR_PEDIDO_EXITO";
export const AGREGAR_PEDIDO_ERROR = "AGREGAR_PEDIDO_ERROR";
