export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";

export const FILTRAR_PRODUCTO = "FILTRAR_PRODUCTO";
export const FILTRAR_PRODUCTO_ERROR = "FILTRAR_PRODUCTO_ERROR";
export const FILTRAR_PRODUCTO_FILTRO = "FILTRAR_PRODUCTO_FILTRO";
